name: C/C++ CI

on:
  push:
    branches: master
    paths:
    - .github/workflows/c-cpp.yml
    - meson.build
    - '**.[ch]'
  pull_request:
    branches: master
    paths:
    - .github/workflows/c-cpp.yml
    - meson.build
    - '**.[ch]'

permissions: {}

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt install libbsd-dev meson
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: build
      run: |
        meson setup build
        ninja -C build
  
  macOS:
    runs-on: macos-latest
    steps:
    - name: Install dependencies
      run: brew install meson
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: build
      run: |
        meson setup build
        ninja -C build
  
  openbsd:
    runs-on: macos-12
    steps:
    - name: Bootstrap OpenBSD
      uses: mario-campos/emulate@v1
      with:
        operating-system: openbsd-latest
    - name: Install dependencies
      run: pkg_add meson
    - name: Checkout repository
      run: git clone --depth 1 https://github.com/mario-campos/xget.git
    - name: build
      run: |
        meson setup build xget
        ninja -C build

  freebsd:
    runs-on: macos-12
    steps:
    - name: Bootstrap FreeBSD
      uses: mario-campos/emulate@v1
      with:
        operating-system: freebsd-latest
    - name: Install dependencies
      run: pkg install -y pkgconf openssl meson
    - name: Checkout repository
      run: git clone --depth 1 https://github.com/mario-campos/xget.git
    - name: build
      run: |
        meson setup build xget
        ninja -C build
