name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  non-bsd:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: build
      run: make

  bsd:
    strategy:
      matrix:
        os: [ openbsd-latest, freebsd-latest ]
    runs-on: macos-10.15
    steps:
    - name: Bootstrap ${{ matrix.os }}
      uses: mario-campos/emulate@v1
      with:
        operating-system: ${{ matrix.os }}
    - name: Checkout repository
      run: git clone --depth 1 https://github.com/mario-campos/xdccget.git
    - name: build
      run: cd xdccget; make
