name: C/C++ CI

on:
  push:
    branches: [ master ]
    paths-ignore:
    - README.md
    - LICENSE
    - .gitignore
    - .github/workflows/codeql-analysis.yml
  pull_request:
    branches: [ master ]

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  discussions: none
  id-token: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: build
      run: make
  
  macOS:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: build
      run: make
      env:
        PKG_CONFIG_PATH: /usr/local/Cellar/openssl@1.1/1.1.1l_1/lib/pkgconfig
  
  openbsd:
    runs-on: macos-10.15
    steps:
    - name: Bootstrap OpenBSD
      uses: mario-campos/emulate@v1
      with:
        operating-system: openbsd-latest
    - name: Checkout repository
      run: git clone --depth 1 https://github.com/mario-campos/xdccget.git
    - name: build
      run: cd xdccget; make

  freebsd:
    runs-on: macos-10.15
    steps:
    - name: Bootstrap FreeBSD
      uses: mario-campos/emulate@v1
      with:
        operating-system: freebsd-latest
    - name: Install dependencies
      run: pkg install -y pkgconf openssl
    - name: Checkout repository
      run: git clone --depth 1 https://github.com/mario-campos/xdccget.git
    - name: build
      run: cd xdccget; make
