name: Clang Analyzer

on:
  push:
    branches: master
    paths:
    - .github/workflows/clang-analyzer.yml
    - meson.build
    - '**.[ch]'
  pull_request:
    branches: master
    paths:
    - .github/workflows/clang-analyzer.yml
    - meson.build
    - '**.[ch]'
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get install -qq libbsd-dev meson clang-tidy
    
    - name: Download clang-tidy-sarif
      run: |
        curl -sSL https://github.com/psastras/sarif-rs/releases/download/clang-tidy-sarif-latest/clang-tidy-sarif-x86_64-unknown-linux-gnu -o "$RUNNER_TEMP/clang-tidy-sarif"
        chmod +x "$RUNNER_TEMP/clang-tidy-sarif"

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build
      run: |
        meson setup build
        ninja -C build

    - name: Run clang-tidy
      run: |
        clang-tidy -p build --checks 'clang-analyzer-*' xget.c -- -D_FILE_OFFSET_BITS=64 $(pkg-config --cflags libbsd-overlay) \
        | "$RUNNER_TEMP/clang-tidy-sarif" \
        | jq ".runs[].results[].locations[].physicalLocation.artifactLocation.uri |= sub(\"$GITHUB_WORKSPACE/\"; \"\")" \
        > clang-results.sarif
  
    - name: Upload SARIF results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: clang-results.sarif     
