name: Cppcheck

on:
  push:
    branches: [ master ]
    paths:
    - .github/workflows/cppcheck.yml
    - '**.[ch]'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install cppcheck
      run: sudo apt-get install -qq cppcheck libbsd-dev meson
    - name: Build
      run: |
        meson setup build
        ninja -C build
    - name: Run cppcheck
      run: >
        cppcheck
        --quiet
        --force
        --enable=all
        --error-exitcode=1
        --project=build/compile_commands.json
        --suppress=ctunullpointer:libircclient/src/colors.c:49
        --suppress=invalidLifetime:libircclient/src/libircclient.c:709
        --suppress=invalidLifetime:libircclient/src/libircclient.c:746