name: FlawFinder

on:
  push:
    branches: master
    paths:
    - .github/workflows/flawfinder.yml
    - meson.build
    - '**.[ch]'
  pull_request:
    branches: master
    paths:
    - .github/workflows/flawfinder.yml
    - meson.build
    - '**.[ch]'
  workflow_dispatch:

jobs:
  flawfinder:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: flawfinder_scan
        uses: david-a-wheeler/flawfinder@2.0.19-alpha1
        with:
          arguments: '--sarif ./'
          output: flawfinder.sarif
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: flawfinder.sarif
