name: FlawFinder

on:
  push:
    branches: master
    paths:
    - .github/workflows/flawfinder.yml
    - meson.build
    - '**.[ch]'
  pull_request:
    branches: master
    paths:
    - .github/workflows/flawfinder.yml
    - meson.build
    - '**.[ch]'
  workflow_dispatch:

jobs:
  flawfinder:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install flawfinder
      - run: flawfinder --quiet --columns .
