name: NASA's IKOS Analyzer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    container: charlesdaniels/ikos_ubuntu
    steps:
    - name: Install dependencies
      run: apt install libbsd-dev meson
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run IKOS
      run: |
        meson setup build
        ikos-scan ninja -C build
