name: NASA's IKOS Analyzer

on:
  push:
    branches: [ master ]
    paths:
    - .github/workflows/ikos.yml
    - '**.[ch]'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-ikos:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: >
        sudo apt-get install -qq 
        libgmp-dev
        libboost-{dev,filesystem-dev,thread-dev,test-dev}
        python3-pygments
        libtbb-dev
        libz-dev
        libedit-dev
        llvm-9{,-dev,-tools}
        clang-9
        
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: NASA-SW-VnV/ikos
        ref: v3.0
  
    - name: Build IKOS
      run: |
        mkdir build "$RUNNER_TEMP/ikos"
        cd build
        cmake "-DCMAKE_INSTALL_PREFIX=$RUNNER_TEMP/ikos" "-DLLVM_CONFIG_EXECUTABLE=$(command -v llvm-config-9)" ..
        make

    - name: Test IKOS
      run: make check
      working-directory: ${{ github.workspace }}/build

    - name: Install IKOS
      run: sudo make install
      working-directory: ${{ github.workspace }}/build

    - name: Bundle and Export IKOS
      uses: actions/upload-artifact@v2
      with:
        path: ${{ runner.temp }}/ikos

  analyze:
    runs-on: ubuntu-latest
    needs: build-ikos
    steps:
    - name: Install dependencies
      run: sudo apt-get install -qq libbsd-dev meson
      
    - name: Install IKOS
      uses: actions/download-artifact@v2
      with:
        path: ${{ runner.temp }}/ikos
      
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run IKOS
      run: |
        meson setup build
        "$RUNNER_TEMP/ikos/bin/ikos-scan" ninja -C build
