name: NASA's IKOS Analyzer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-ikos:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: >
        sudo apt-get install -qq 
        libgmp-dev
        libboost-{dev,filesystem-dev,thread-dev,test-dev}
        python3-pygments
        libtbb-dev
        libz-dev
        libedit-dev
        llvm-10{,-dev,-tools}
        
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: NASA-SW-VnV/ikos
        ref: v3.0
  
    - name: Build IKOS
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DLLVM_CONFIG_EXECUTABLE=$(command -v llvm-config-10) ..
        make

    - name: Test IKOS
      run: make check
      working-directory: ${{ github.workspace }}/build

    - name: Install IKOS
      run: sudo make install
      working-directory: ${{ github.workspace }}/build

  analyze:
    runs-on: ubuntu-latest
    needs: build-ikos
    steps:
    - name: Install dependencies
      run: sudo apt-get install -qq libbsd-dev meson
      
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run IKOS
      run: |
        meson setup build
        ikos-scan ninja -C build
