name: NASA's IKOS Analyzer

on:
  push:
    branches: [ master ]
    paths:
    - .github/workflows/ikos.yml
    - '**.[ch]'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    container: ghcr.io/mario-campos/ikos-dockerfile:3.0-1
    steps:
    - name: Install dependencies
      run: apt-get install -qq libbsd-dev meson
      
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run IKOS
      run: |
        meson setup build
        ikos-scan ninja -C build