name: Infer

on:
  push:
    branches: master
    paths:
    - .github/workflows/infer.yml
    - meson.build
    - '**.[ch]'
  pull_request:
    branches: master
    paths:
    - .github/workflows/infer.yml
    - meson.build
    - '**.[ch]'
  workflow_dispatch:

jobs:
  run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install meson infer

      - name: Build xget
        run: |
          meson setup build
          ninja -C build

      - name: Run Infer
        run: infer --compilation-database build/compile_commands.json
